<a href="https://colab.research.google.com/github/hugemartyr/PytorchTinkerings/blob/main/pytorchTinkerings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__
scalar= torch.tensor(7)

scalar.item()



7

In [ ]:

import torch
torch.__version__
vector1= torch.rand(size=(3,4,5), dtype=torch.float64)
vector2= torch.rand(size=(3,5,5), dtype=torch.float64)
torch.matmul(vector1, vector2)



tensor([[[1.3087, 0.7132, 0.6957, 1.1423, 1.1824],
         [1.4824, 0.8119, 0.4780, 1.4327, 0.9896],
         [1.6104, 0.6933, 0.8547, 2.0084, 0.6549],
         [1.4848, 0.8876, 0.5981, 1.3040, 1.0576]],

        [[1.2947, 1.8769, 0.7934, 2.1384, 1.0168],
         [1.3665, 1.5181, 1.2687, 1.5927, 0.9121],
         [0.8691, 1.3688, 0.5277, 1.7011, 0.6323],
         [0.5085, 0.9667, 0.2992, 0.9763, 0.3115]],

        [[0.5444, 0.2357, 0.4053, 0.4628, 0.7034],
         [1.6155, 0.9957, 1.5244, 0.6370, 1.9745],
         [1.4264, 0.4420, 1.1426, 1.0552, 1.9779],
         [0.6488, 0.1479, 0.4083, 0.8535, 0.8916]]], dtype=torch.float64)

In [ ]:

import torch
torch.__version__
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

NameError: ignored

In [ ]:
import torch
torch.__version__
torch.manual_seed(1234)
torch.cuda.manual_seed(123)
vector1= torch.rand(size=(7,7),dtype=torch.float32)
vector2=torch.rand(size=(1,7),dtype=torch.float32)
torch.mm(vector1, vector2.T)


tensor([[1.5166],
        [3.1874],
        [2.5350],
        [2.8343],
        [2.6844],
        [2.6483],
        [2.4059]])

In [ ]:
import torch
torch.__version__
torch.manual_seed(0)

if torch.cud.is_available():
  num=torch.cuda.device_count()
  print("the GPUs available are :: ",num)
  vector1= torch.rand(size=(2,7)).to(device)
  vector2= torch.rand(size= (3,7)).to(device)
  torch.mm( vector1, vector2.T)
else:
  print("No GPUs available")

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False


NameError: ignored

In [ ]:
import torch

# Set the random seed for CPU
torch.manual_seed(0)

# Check if CUDA (GPU support) is available
if torch.cuda.is_available():
    # Set the random seed for GPU
    torch.cuda.manual_seed(0)
    torch.cuda.manual_seed_all(0)

In [ ]:

import torch
torch.__version__
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

NameError: ignored

In [ ]:
import torch
torch.__version__
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B


NameError: ignored

In [5]:
import torch


if torch.cuda.is_available():

    tensor1 = torch.rand(1, 7).to(torch.device("cuda"))
    tensor2 = torch.rand(6, 7).to(torch.device("cuda"))


    result = tensor1 + tensor2

    # Move the result back to the CPU (if needed)
    result = result.to(torch.device("cpu"))

    print("Tensor 1 on GPU:")
    print(tensor1)
    print("Tensor 2 on GPU:")
    print(tensor2)
    print("Result on CPU:")
    print(result)
else:
    print("GPU is not available.")


Tensor 1 on GPU:
tensor([[0.9952, 0.4957, 0.1500, 0.3557, 0.8829, 0.7015, 0.7016]],
       device='cuda:0')
Tensor 2 on GPU:
tensor([[0.4982, 0.9412, 0.6679, 0.2497, 0.9673, 0.1014, 0.6686],
        [0.1402, 0.2364, 0.5618, 0.6230, 0.6497, 0.2721, 0.6236],
        [0.0516, 0.2377, 0.2953, 0.9223, 0.9556, 0.5098, 0.8716],
        [0.3602, 0.8874, 0.6815, 0.2584, 0.2260, 0.0931, 0.1947],
        [0.2427, 0.6690, 0.0238, 0.1292, 0.9941, 0.8839, 0.0831],
        [0.1049, 0.1058, 0.6191, 0.6188, 0.2409, 0.9833, 0.1516]],
       device='cuda:0')
Result on CPU:
tensor([[1.4934, 1.4369, 0.8179, 0.6054, 1.8502, 0.8029, 1.3702],
        [1.1355, 0.7321, 0.7118, 0.9787, 1.5326, 0.9736, 1.3252],
        [1.0468, 0.7334, 0.4453, 1.2780, 1.8385, 1.2114, 1.5732],
        [1.3555, 1.3830, 0.8315, 0.6141, 1.1089, 0.7946, 0.8963],
        [1.2380, 1.1647, 0.1739, 0.4849, 1.8770, 1.5855, 0.7847],
        [1.1001, 0.6015, 0.7691, 0.9745, 1.1238, 1.6848, 0.8532]])


In [8]:
import torch


if torch.cuda.is_available():
  device= torch.device("cuda")
  print("GPU is available and used")

else:
  device= torch.device("cpu")
  print("CPU is available and used")


tensor1 = torch.rand(1, 7).to(torch.device("cuda"))
tensor2 = torch.rand(6, 7).to(torch.device("cuda"))
result= torch.mm( tensor1, tensor2.T)

print("The matmul is :", result)



GPU is available and used
The matmul is : tensor([[2.2851, 2.3643, 1.6883, 1.5501, 1.5787, 1.7798]], device='cuda:0')


In [10]:
import torch


if torch.cuda.is_available():
  device= torch.device("cuda")
  print("GPU is available and used")

else:
  device= torch.device("cpu")
  print("CPU is available and used")


tensor1 = torch.rand( size=(3,4), device="cuda")
tensor2 = torch.rand( size=(3,4), device="cuda")
result= torch.mm( tensor1, tensor2.T)

print("The matmul is :", result)

GPU is available and used
The matmul is : tensor([[1.4852, 1.2423, 1.5385],
        [1.0881, 0.9462, 0.7647],
        [0.9150, 0.7804, 0.5192]], device='cuda:0')
